global:
  message: Welcome to global Microservices Environment!!
logging:
  level:
    root: INFO
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
