server:
  port: 8080
  
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: 
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
      routes:
        - id: pet-service-route
          uri: lb://pet-service
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=1
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: chat_ws
          uri: lb://chat-service
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1
      websocket:
        enabled: true
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
