spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders: "*"
      routes:
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/api/pets/**
          filters:
            - StripPrefix=1
            
        - id: chat-service-rest
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
            
        - id: chat-service-ws
          uri: lb:ws://chat-service
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1
            
      websocket:
        enabled: true
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
