spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

resilience4j:
  circuitbreaker:
    instances:
      userService:
        minimumNumberOfCalls: 20               # Cantidad mínima de llamadas para evaluar el estado
        failureRateThreshold: 50               # Si más del 50% fallan, se abre el circuito
        waitDurationInOpenState: 10s           # Tiempo que queda abierto el circuito antes de intentar nuevamente
        permittedNumberOfCallsInHalfOpenState: 5 # Llamadas permitidas en estado "medio abierto"
        slidingWindowSize: 100                 # Cantidad de llamadas consideradas para calcular el ratio
        slidingWindowType: COUNT_BASED         
