spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        minimumNumberOfCalls: 100
        failureRateThreshold: 100
        waitDurationInOpenState: 1ms
