global:
  message: Welcome to pet service prod environment!!
message: Hello from Prod!

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  user-service:
    url: ${USER_SERVICE_URL}

server:
  port: 8082

resilience4j:
  circuitbreaker:
    instances:
      userService:
        minimumNumberOfCalls: 20               # Cantidad mínima de llamadas para evaluar el estado
        failureRateThreshold: 50               # Si más del 50% fallan, se abre el circuito
        waitDurationInOpenState: 10s           # Tiempo que queda abierto el circuito antes de intentar nuevamente
        permittedNumberOfCallsInHalfOpenState: 5 # Llamadas permitidas en estado "medio abierto"
        slidingWindowSize: 100                 # Cantidad de llamadas consideradas para calcular el ratio
        slidingWindowType: COUNT_BASED         

  retry:
    instances:
      userService:
        maxAttempts: 3                         # Máximo de intentos
        waitDuration: 1s                       # Espera entre intentos
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
