global:
  message: Welcome to user service dev environment!!
message: Hello from Dev!

spring:
  datasource:
    url: ${USER_DATASOURCE_URL}
    username: ${USER_DATASOURCE_USERNAME}
    password: ${USER_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
